### ISSUE TITLE
Is this ready?

### ISSUE THREAD

**Issue by aikar** [christensson/eslint-plugin-no-await-async-call#2]
Hi, this plugin looks pretty good to avoid some easy to hit bugs!

I see it is not published yet. Do you have an ETA on when it will be ready?

**Comment by christensson** [comment]
Yes, my intention with this plugin was to detect when forgetting the `await` keyword (which I do a lot...)

I haven't worked on it for a while, but as I remember it, ES6 classes is not fully supported yet as mentioned by issue #1. I don't remember which cases though...

**Comment by sweth** [comment]
Any chance you could go ahead an publish it?  I'm using it regularly, but it inevitably causes confusion when I point someone else to it and they try to npm install it and then I have to explain to them how to point npm to a local clone of the repo to get it to install...

**Comment by christensson** [comment]
@sweth published as is: https://www.npmjs.com/package/eslint-plugin-no-await-async-call
